version: 2
jobs:
  build:
    docker:
      - image: greenbone/build-env-openvas-smb-master-debian-buster-gcc-core
    steps:
      - checkout
      - run:
          name: Configure and Compile
          command: mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install
